### ISSUE TITLE
SUPEE-6788 breaks functionality

### ISSUE THREAD

**Issue by mraabhimself** [xonu/SBE#2]
I applied patch SUPEE-6788 to my store and everywhere I've used SBE, there is no output.

I'm not sure if it's able to be reimplemented or what have you, but I figured I'd at least give you the information.

Please forgive me if Google Translate borked the translation.

Ich bewarb mich Patch SUPEE-6788 zu meinem Speicher und überall habe ich SBE verwendet wird, erfolgt keine Ausgabe.

Ich bin mir nicht sicher, ob es in der Lage, neu implementiert werden, ist oder was auch immer, aber ich dachte, ich würde zumindest die Informationen geben Ihnen.

**Comment by xonu** [comment]
Thank you very much for this report. We will check and fix this issue, as soon as possible.

**Comment by xonu** [comment]
To resolve this issue, please go to System > Permissions > Blocks and add a new block with the block name cms/block (Allowed=Yes).

**Comment by mraabhimself** [comment]
Great! Glad you found a solution.

Thanks a bunch!
